--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/tedo0627/InventoryUI
build-by-default: true
branches:
- master
projects:
  InventoryUI:
    path: ""
    model: virion
    type: library
...
